# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:29
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20170304_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
