# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20170305_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=models.CharField(max_length=20000),
        ),
    ]
