# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20170306_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=models.TextField(),
        ),
    ]
