# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20170306_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=models.TextField(),
        ),
    ]
