# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20170306_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
