# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20170306_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
