# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:06
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20170310_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
