# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_auto_20170310_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
