# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 07:02
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_auto_20170311_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
