# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0021_auto_20170311_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='ref',
            field=models.ManyToManyField(to='myblog.Reference'),
        ),
    ]
