# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_auto_20170311_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ref_title1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title5',
            field=models.CharField(max_length=1000),
        ),
    ]
