# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0026_auto_20170311_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='source',
            new_name='source_url',
        ),
    ]
