# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0028_auto_20170311_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ref_title1',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title2',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title3',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title4',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ref_title5',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
    ]
