# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0029_auto_20170312_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=0),
        ),
    ]
