# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0030_auto_20170312_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
