# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0032_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='MySearch',
        ),
    ]
