# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0033_auto_20170313_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySearch',
        ),
    ]
