# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0034_delete_mysearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='MyReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
