# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0035_myevent_myreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevent',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myreference',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
