# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0036_auto_20170313_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreference',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
