# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0039_mycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='comments',
            field=models.ManyToManyField(to='myblog.MyComment'),
        ),
    ]
