# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0040_myblog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='comments',
        ),
        migrations.DeleteModel(
            name='MyComment',
        ),
    ]
