# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0042_auto_20170313_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, '計画中'), (2, '進行中'), (3, '実装済')], default=1),
        ),
    ]
