# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0044_auto_20170313_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='genre',
            field=models.IntegerField(choices=[(1, b'Life'), (2, b'Coding'), (3, b'Recruit'), (4, b'Project'), (5, b'AI'), (6, b'Others')], default=0),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_title1',
            field=models.CharField(blank=True, default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_title2',
            field=models.CharField(blank=True, default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_title3',
            field=models.CharField(blank=True, default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_title4',
            field=models.CharField(blank=True, default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_title5',
            field=models.CharField(blank=True, default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_url3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_url4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='ref_url5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
