# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0045_auto_20170317_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='myblog',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
