# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0046_auto_20170319_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
