# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 10:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0046_auto_20170319_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name=b'default'),
        ),
    ]
