# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 01:17
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0047_auto_20170416_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
